[common]
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit GFX Library@^1.11.9

    earlephilhower/ESP8266Audio@^1.9.7
    greiman/SdFat@^2.2.3

; --- Real hardware (Adafruit Feather ESP32-S3) ---
[env:feather]
platform = espressif32
board = adafruit_feather_esp32s3
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
build_flags =
    -DBOARD_HAS_PSRAM

; --- Wokwi simulation (ESP32-S3 DevKitC-1) ---
[env:sim]
platform = espressif32
board = esp32-s3-devkitc-1
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps = ${common.lib_deps}
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
extra_scripts = merge_firmware.py
